/**
 * Services Index
 * Central export for all backend services
 */

// Homepage GAS Service
export {
  fetchHomepageContent,
  fetchHomepageContentSafe,
  updateHomepageContent,
  clearHomepageCache,
  getDefaultHomepageContent,
  checkHomepageApiHealth,
  HomepageAPIError,
  type HomepageMainContent,
  type HomepageHeroContent,
  type HomepageAboutContent,
  type HomepageMissionContent,
  type HomepageVisionContent,
  type HomepageAdvocacyPillarsContent,
  type GASError,
  // Homepage_Other (Contact Section) exports
  fetchHomepageOtherContent,
  fetchHomepageOtherContentSafe,
  updateHomepageOtherContent,
  uploadOrgChart,
  addSocialLink,
  removeSocialLink,
  updateSocialLink,
  clearHomepageOtherCache,
  getDefaultHomepageOtherContent,
  type HomepageOtherContent,
  type SocialLinkData,
  // Dev Info (Developer Profile) exports
  fetchDevInfoContent,
  fetchDevInfoContentSafe,
  updateDevInfoContent,
  uploadDevProfile,
  addDevAffiliation,
  removeDevAffiliation,
  updateDevAffiliation,
  addDevSocialLink,
  removeDevSocialLink,
  updateDevSocialLink,
  clearDevInfoCache,
  getDefaultDevInfoContent,
  type DevInfoContent,
  type DevAffiliationData,
  type DevSocialLinkData,
} from './gasHomepageService';

// Login GAS Service
export {
  authenticateUser,
  checkLoginApiHealth,
  fetchUserProfile,
  updateUserProfile,
  storeSession,
  getSessionToken,
  getStoredUser,
  clearSession,
  hasActiveSession,
  verifySession,
  getRoleDisplayName,
  hasAdminAccess,
  hasLeadershipAccess,
  isRestricted,
  LoginErrorCodes,
  LoginAPIError,
  type LoginUser,
  type LoginResponse,
  type SessionVerifyResponse,
  type UserProfile,
  type ProfileResponse,
  type ProfileUpdateResponse,
} from './gasLoginService';

// Directory GAS Service
export {
  searchOfficers,
  getOfficerByIdCode,
  getAllOfficers,
  clearDirectoryCache,
  checkDirectoryApiHealth,
  getRoleDisplayName as getDirectoryRoleDisplayName,
  getRoleBadgeColor,
  DirectoryErrorCodes,
  DirectoryAPIError,
  type DirectoryOfficer,
  type SearchOfficersResponse,
  type GetOfficerResponse,
  type GetAllOfficersResponse,
} from './gasDirectoryService';

// Events GAS Service
export {
  fetchEvents,
  fetchEventsSafe,
  fetchEventById,
  fetchUpcomingEvents,
  fetchPastEvents,
  createEvent,
  updateEvent,
  deleteEvent,
  cancelEvent,
  duplicateEvent,
  fetchEventAttendance,
  recordEventAttendance,
  bulkRecordEventAttendance,
  fetchEventStats,
  initializeEventSheets,
  checkEventsApiHealth,
  clearEventsCache,
  clearAllEventsCache,
  getEventGeofence,
  formatEventDate,
  formatEventTime,
  isEventUpcoming,
  isEventPast,
  EventsErrorCodes,
  EventsAPIError,
  type EventData,
  type EventAttendanceRecord,
  type EventStats,
  type CreateEventData,
  type GASEventsResponse,
} from './gasEventsService';

// Attendance GAS Service
export {
  recordTimeIn,
  recordTimeOut,
  recordManualAttendance,
  checkExistingAttendance,
  getEventAttendanceRecords,
  getMemberAttendanceHistory,
  getMembersForAttendance,
  clearMembersCache,
  validateGeofence,
  checkAttendanceApiHealth,
  isAttendanceApiConfigured,
  AttendanceErrorCodes,
  AttendanceAPIError,
  type AttendanceRecord,
  type MemberForAttendance,
  type RecordTimeInParams,
  type RecordTimeOutParams,
  type RecordManualAttendanceParams,
  type TimeInResponse,
  type TimeOutResponse,
  type ManualAttendanceResponse,
  type ExistingAttendanceResponse,
  type GeofenceValidationResponse,
} from './gasAttendanceService';
